  name: Workflow - Feature
  on:
    push:
      branches:
        - 'feature/*'
  jobs:
    prepare:
      runs-on: ubuntu-20.04
      steps:
        - uses: actions/checkout@v3
        - run: chmod +x gradlew
        - run: |
            GOOGLE_SERVICES_FILE="app/google-services.json"
            DEVELOPMENTDEBUG_GOOGLE_SERVICES_FILE="app/src/developmentDebug/google-services.json"
            DEBUG_GOOGLE_SERVICES_FILE="app/src/debug/google-services.json"
            DEVELOPMENT_GOOGLE_SERVICES_FILE="app/src/development/google-services.json"
            DEVELOPMENT_DEBUG_GOOGLE_SERVICES_FILE="app/src/development/debug/google-services.json"
            DEBUG_DEVELOPMENT_GOOGLE_SERVICES_FILE="app/src/debug/development/google-services.json"
            echo "${{ secrets.GOOGLE_SERVICES }}"> GOOGLE_SERVICES_FILE
            echo "${{ secrets.GOOGLE_SERVICES }}"> DEVELOPMENTDEBUG_GOOGLE_SERVICES_FILE
            echo "${{ secrets.GOOGLE_SERVICES }}"> DEBUG_GOOGLE_SERVICES_FILE
            echo "${{ secrets.GOOGLE_SERVICES }}"> DEVELOPMENT_GOOGLE_SERVICES_FILE
            echo "${{ secrets.GOOGLE_SERVICES }}"> DEVELOPMENT_DEBUG_GOOGLE_SERVICES_FILE
            echo "${{ secrets.GOOGLE_SERVICES }}"> DEBUG_DEVELOPMENT_GOOGLE_SERVICES_FILE
        - run: |
            KEYSTORE_P12_ASC_FILE="keystore.asc"
            echo "${{ secrets.KEYSTORE_P12 }}">> ${KEYSTORE_P12_ASC_FILE}
            gpg -d \
              --batch \
              --passphrase "$(echo "${{ secrets.PASSWORD }}" | base64 --decode)" \
            "${KEYSTORE_P12_ASC_FILE}"> "keystore.p12"
        - run: |
            KEYSTORE_PROPERTIES_ASC_FILE="keystore_properties.asc"
            echo "${{ secrets.KEYSTORE_PROPERTIES }}">> ${KEYSTORE_PROPERTIES_ASC_FILE}
            gpg -d \
            --batch \
            --passphrase "$(echo "${{ secrets.PASSWORD }}" | base64 --decode)" \
            "${KEYSTORE_PROPERTIES_ASC_FILE}"> "keystore.properties"
        - run: ./gradlew test
