  name: Workflow - Feature
  on:
    push:
      branches:
        - 'feature/*'
  jobs:
    pass_tests:
      runs-on: ubuntu-20.04
      steps:
        - run: |
            echo "${{ secrets.GOOGLE_SERVICES }}"> "../app/google-services.json"
        - run: ./gradlew test
